batch_size: 16
patch_size: [16, 16, 16]
in_channels: 1
img_size: [128, 128, 128]
out_channels: 1
deconv_chns: 16
hidden_size: 384
mlp_dim: 3072
num_layers: 8
num_heads: 8
dropout_rate: 0.0
qkv_bias: False
save_attn: True
n_epochs: 300
max_epochs: 300
bids_root: /home/gmarti/DATA/DHCP_FETAL/dhcp_anat_pipeline/
modality: T2w
spacing: [1.0, 1.0, 1.0]
ratios: [0.8, 0.1, 0.1]

progress_bar_refresh_rate: 1
check_val_every_n_epoch: 1
enable_progress_bar: 1
log_every_n_steps: 1
gpus: 1